### ISSUE TITLE
Language audio output

### ISSUE THREAD

**Issue by AlexMeier99** [yaxarat/lingvaandroid#2]
Hi @yaxarat,
I love the app. Hope you'd have the time to implement more features. I'd like to pass one a few ideas and sources to support the development.

Related to step one of the **roadmap**: https://developer.android.com/guide/topics/media/mediaplayer#kotlin to my understanding playing audio through `MediaPlayer` should do the trick.

Regards,
Alexei

**Comment by AlexMeier99** [comment]
Translating the app itself would be great as well. Managing the translations through weblate an open source SaaS for translations might ease that.

**Comment by yaxarat** [comment]
Thank you for the feedback and the feature request! I actually have a local branch working on that at the moment. I apologize for the delay, but the past month or so have been super blocked due to some personal reasons. With that said, the development should pick up soon 🤞🏼 . Also, if there is a feature you want and are confident implementing, feel free to open up a PR. This is an open-source project after all :)

**Comment by yaxarat** [comment]
Just updating to point out this will be implemented in the next release or release after. Thanks for the patience.
